package org.httprobot;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

public class Enums {

	public enum EventType {
		CLI,
		XML,
		CONTROL,
		MANAGER,
		DATA,
		NET
	}
	public enum ContentEventType
	{
		DOCUMENT_ADDED,
		DOCUMENT_REMOVED,
		DOCUMENT_COMPLETED,
		FIELD_ADDED,
		FIELD_REMOVED,
		FIELD_CHANGED
	}
	public enum WebServiceEventType {
		CONFIGURATION
	}
	public enum XmlEventType {
		SET_UUID,
		MESSAGE_MARSHALLED,
		MESSAGE_UNMARSHALLED
	}
	public enum ControlEventType
	{
		INIT,
		LOAD
	}
	public enum ManagerEventType {
		PARAMETER_CONSTANT_ADDED,
		PARAMETER_BANNED_WORD_ADDED,
		DATA_SOURCE_LIST_LOADED,
		DATA_SOURCE_LOADED,
		DOCUMENT_COMPLETED,
		DOCUMENT_INITIALIZED,
		FIELD_COMPLETED,
		ERROR,
		FINISHED,
		PAGE_LOADED,
		STARTED,
		SYSTEM_CONTENT_TYPE_ROOT_LOADED,
		ACTION_WEB_LOADED
	}
	public enum Command {
		SET_PATH,
		CONSTANT_CONTROL_LOADED,
		BANNED_WORD_CONTROL_LOADED,
		SERVER_URL_CONTROL_LOADED,
		START_URL_CONTROL_LOADED,
		ACTION_CONTROL_LOADED,
		IS_INSTANCE_CONTROL_LOADED,
		CONFIGURATION_CONTROL_LOADED,
		CONTAINS_CONTROL_LOADED,
		STARTS_WITH_CONTROL_LOADED,
		ENDS_WITH_CONTROL_LOADED,
		CONTENT_TYPE_CONTROL_LOADED,
		CONTENT_TYPE_REF_CONTROL_LOADED,
		CONTENT_TYPE_ROOT_CONTROL_LOADED,
		DATA_SOURCE_CONTROL_LOADED,
		DATA_VIEW_CONTROL_LOADED,
		TO_UPPER_CASE_CONTROL_LOADED,
		TO_LOWER_CASE_CONTROL_LOADED,
		END_INDEX_CONTROL_LOADED,
		EQUALS_CONTROL_LOADED,
		FIELD_CONTROL_LOADED,
		FIELD_REF_CONTROL_LOADED,
		FIELD_ROOT_CONTROL_LOADED,
		HTML_UNIT_CONTROL_LOADED,
		HTTP_ADDRESS_CONTROL_LOADED,
		LOG_CONTROL_LOADED,
		PAGINATOR_CONTROL_LOADED,
		TRIM_CONTROL_LOADED,
		REPLACE_CONTROL_LOADED,
		SERVICE_CONNECTION_CONTROL_LOADED,
		SESSION_CONTROL_LOADED,
		CONCAT_CONTROL_LOADED,
		START_INDEX_CONTROL_LOADED,
		DOCUMENT_CONTROL_LOADED,
		DOCUMENT_ROOT_CONTROL_LOADED,
		SUBSTRING_CONTROL_LOADED,
		TRY_PARSE_CONTROL_LOADED,
		WEB_LOADER_CONTROL_LOADED,
		PAGE_CONTROL_LOADED,
		ANCHOR_CONTROL_LOADED,
		ELEMENT_CONTROL_LOADED,
		CONTAINS_ELEMENT_CONTROL_LOADED,
		DIVISION_CONTROL_LOADED,
		TABLE_CONTROL_LOADED,
		TABLE_ROW_CONTROL_LOADED,
		TABLE_CELL_CONTROL_LOADED,
		WEB_SERVICE_CONTROL_LOADED,
		MESSAGE,
		RUN_WEB_REQUEST,
		SET_DESTINATION_PATH,
		SET_UUID,
		SET_OPTIONS,
		TREAT_WEB_RESPONSE
	}
	public enum Data {
		UUID,
		Q_NAME,
		URL,
		CONTENT_TYPE_ROOT,
		DATA_SOURCE,
		INHERITED_TYPE,
		CONTENT_TYPE,
		CONTENT_TYPE_REF,
		FIELD_REF,
		NAME,
		NTP,
		SOURCE_NAME,
		FIELD_NAME,
		FIELD_TYPE,
		ACTION,
		DOCUMENT_ROOT,
		DOCUMENT,
		SERVER_URL,
		START_URL,
		FIELD_ROOT,
		FIELD,
		HTTP_ADDRESS,
		HTML_UNIT,
		KEY,
		PARAMETER_TYPE,
		VALUE,
		CONTAINS,
		EQUALS,
		TRIM,
		REPLACE,
		CONCAT,
		STARTS_WITH,
		ENDS_WITH,
		TO_UPPER_CASE,
		TO_LOWER_CASE,
		SUBSTRING,
		TRY_PARSE,
		PAGE,
		PAGINATOR,
		PAGINATOR_HREF,
		PAGINATOR_ANCHOR,
		PAGINATOR_INCREMENT,
		PAGINATOR_URL_PATTERN,
		STRICT_MODE,
		METHOD,
		IS_INSTANCE,
		WEB_LOADER,
		BANNED_WORD,
		CONSTANT,
		DELIMITER,
		STRING_VALUE,
		INTEGER_VALUE,
		OFFSET,
		START_INDEX,
		END_INDEX,
		OLD_STRING,
		NEW_STRING,
		HREF,
		HREF_LANG,
		TEXT_CONTENT,
		CHARSET,
		TYPE,
		TARGET,
		ID,
		STYLE,
		CLASS_NAME,
		TITLE,
		NODE_NAME,
		XPATH,
		TAG_NAME,
		ANCHOR,
		ELEMENT,
		SERVICE_CONNECTION,
		TIME,
		BROWSER_VERSION,
		CONTAINS_ELEMENT
	}
	@XmlEnum
	public enum ParameterType
	{
		@XmlEnumValue(value = "href-banned")
		BANNED_WORD,
		@XmlEnumValue(value = "href-constant")
		CONSTANT
	}
	@XmlEnum
	public enum DataType
	{
		@XmlEnumValue(value = "BASE64")
		BASE64,
		@XmlEnumValue(value = "BOOLEAN")
		BOOLEAN,
		@XmlEnumValue(value = "DATETIME")
		DATETIME,
		@XmlEnumValue(value = "IMAGE")
		IMAGE,
		@XmlEnumValue(value = "LINK")
		LINK,
		@XmlEnumValue(value = "NUMBER")
		NUMBER,
		@XmlEnumValue(value = "TEXT")
		TEXT,
		@XmlEnumValue(value = "UUID")
		UUID,
		@XmlEnumValue(value = "XML")
		XML
	}
	@XmlEnum
	public enum FieldType
	{
		STRING,
		INTEGER,
		FLOAT,
		DATETIME,
		BOOLEAN,
		URL,
		UUID,
		BASE64,
	}
	@XmlEnum
	public enum HttpRequestType
	{
		@XmlEnumValue(value = "GET")
		GET,
		@XmlEnumValue(value = "POST")
		POST
	}
	@XmlType(name = "UnitBrowserVersion")
	@XmlEnum
	public enum UnitBrowserVersion
	{
		CHROME,
		FIREFOX,
		IE,
		EDGE
	}
}
