package org.httprobot;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

public class Enums {

	public enum Command {
		ACTION_CONTROL_LOADED,
		ANCHOR_CONTROL_LOADED,
		BANNED_WORD_CONTROL_LOADED,
		CONCAT_CONTROL_LOADED,
		CONFIGURATION_CONTROL_LOADED,
		CONSTANT_CONTROL_LOADED,
		CONTAINS_CONTROL_LOADED,
		CONTAINS_ELEMENT_CONTROL_LOADED,
		CONTENT_TYPE_CONTROL_LOADED,
		CONTENT_TYPE_REF_CONTROL_LOADED,
		CONTENT_TYPE_ROOT_CONTROL_LOADED,
		DATA_SOURCE_CONTROL_LOADED,
		DATA_VIEW_CONTROL_LOADED,
		DIVISION_CONTROL_LOADED,
		DOCUMENT_CONTROL_LOADED,
		DOCUMENT_ROOT_CONTROL_LOADED,
		ELEMENT_CONTROL_LOADED,
		END_INDEX_CONTROL_LOADED,
		ENDS_WITH_CONTROL_LOADED,
		EQUALS_CONTROL_LOADED,
		FIELD_CONTROL_LOADED,
		FIELD_REF_CONTROL_LOADED,
		FIELD_ROOT_CONTROL_LOADED,
		HTML_UNIT_CONTROL_LOADED,
		HTTP_ADDRESS_CONTROL_LOADED,
		IS_INSTANCE_CONTROL_LOADED,
		LOG_CONTROL_LOADED,
		MESSAGE,
		PAGE_CONTROL_LOADED,
		PAGINATOR_CONTROL_LOADED,
		REPLACE_CONTROL_LOADED,
		RUN_WEB_REQUEST,
		SERVER_URL_CONTROL_LOADED,
		SERVICE_CONNECTION_CONTROL_LOADED,
		SESSION_CONTROL_LOADED,
		SET_DESTINATION_PATH,
		SET_OPTIONS,
		SET_PATH,
		SET_UUID,
		START_INDEX_CONTROL_LOADED,
		START_URL_CONTROL_LOADED,
		STARTS_WITH_CONTROL_LOADED,
		SUBSTRING_CONTROL_LOADED,
		TABLE_CELL_CONTROL_LOADED,
		TABLE_CONTROL_LOADED,
		TABLE_ROW_CONTROL_LOADED,
		TO_LOWER_CASE_CONTROL_LOADED,
		TO_UPPER_CASE_CONTROL_LOADED,
		TREAT_WEB_RESPONSE,
		TRIM_CONTROL_LOADED,
		TRY_PARSE_CONTROL_LOADED,
		WEB_LOADER_CONTROL_LOADED,
		WEB_SERVICE_CONTROL_LOADED
	}
	public enum ContentEventType
	{
		DOCUMENT_ADDED,
		DOCUMENT_COMPLETED,
		DOCUMENT_REMOVED,
		FIELD_ADDED,
		FIELD_CHANGED,
		FIELD_REMOVED
	}
	public enum ControlEventType
	{
		INIT,
		LOAD
	}
	public enum Data {
		ACTION,
		ANCHOR,
		BANNED_WORD,
		BROWSER_VERSION,
		CHARSET,
		CLASS_NAME,
		CLICK,
		CONCAT,
		CONSTANT,
		CONTAINS,
		CONTAINS_ELEMENT,
		CONTENT_TYPE,
		CONTENT_TYPE_REF,
		CONTENT_TYPE_ROOT,
		DATA_SOURCE,
		DELIMITER,
		DISALLOW_IMAGES,
		DOCUMENT,
		DOCUMENT_ROOT,
		ELEMENT,
		END_INDEX,
		ENDS_WITH,
		EQUALS,
		FIELD,
		FIELD_NAME,
		FIELD_REF,
		FIELD_ROOT,
		FIELD_TYPE,
		HREF,
		HREF_LANG,
		HTML_UNIT,
		HTTP_ADDRESS,
		ID,
		INHERITED_TYPE,
		INTEGER_VALUE,
		IS_INSTANCE,
		JAVASCRIPT,
		KEY,
		METHOD,
		NAME,
		NEW_STRING,
		NEXT_PAGE_ATTRIBUTE,
		NODE_NAME,
		NTP,
		OFFSET,
		OLD_STRING,
		PAGE,
		PAGINATOR,
		PAGINATOR_ANCHOR_TEXT,
		PAGINATOR_HREF,
		PAGINATOR_INCREMENT,
		PAGINATOR_URL_PATTERN,
		PARAMETER_TYPE,
		Q_NAME,
		REPLACE,
		SERVER_URL,
		SERVICE_CONNECTION,
		SOURCE_NAME,
		START_INDEX,
		START_URL,
		STARTS_WITH,
		STORE,
		STRICT_MODE,
		STRING_VALUE,
		STYLE,
		SUBSTRING,
		TAG_NAME,
		TARGET,
		TEXT_CONTENT,
		TIME,
		TITLE,
		TO_LOWER_CASE,
		TO_UPPER_CASE,
		TRIM,
		TRY_PARSE,
		TYPE,
		URL,
		UUID,
		VALUE,
		WEB_LOADER,
		XPATH
	}
	@XmlEnum
	public enum GetMethod
	{
		@XmlEnumValue(value = "CLICK_NEXT_ELEMENT")
		CLICK_NEXT_ELEMENT,
		@XmlEnumValue(value = "HTTP_GET")
		HTTP_GET
	}
	@XmlEnum
	public enum FinalCondition
	{
		@XmlEnumValue(value = "MISSING_ELEMENT")
		MISSING_ELEMENT,
		@XmlEnumValue(value = "END_MESSAGE")
		END_MESSAGE
	}
	@XmlEnum
	public enum DataType
	{
		@XmlEnumValue(value = "BASE64")
		BASE64,
		@XmlEnumValue(value = "BOOLEAN")
		BOOLEAN,
		@XmlEnumValue(value = "DATETIME")
		DATETIME,
		@XmlEnumValue(value = "IMAGE")
		IMAGE,
		@XmlEnumValue(value = "LINK")
		LINK,
		@XmlEnumValue(value = "NUMBER")
		NUMBER,
		@XmlEnumValue(value = "TEXT")
		TEXT,
		@XmlEnumValue(value = "UUID")
		UUID,
		@XmlEnumValue(value = "XML")
		XML
	}
	public enum EventType {
		CLI,
		CONTROL,
		DATA,
		MANAGER,
		NET,
		XML
	}
	@XmlEnum
	public enum FieldType
	{
		BASE64,
		BOOLEAN,
		DATETIME,
		FLOAT,
		INTEGER,
		STRING,
		URL,
		UUID,
	}
	@XmlEnum
	public enum HttpRequestType
	{
		@XmlEnumValue(value = "GET")
		GET,
		@XmlEnumValue(value = "POST")
		POST
	}
	public enum ManagerEventType {
		ACTION_WEB_LOADED,
		DATA_SOURCE_LIST_LOADED,
		DATA_SOURCE_LOADED,
		DOCUMENT_COMPLETED,
		DOCUMENT_INITIALIZED,
		ELEMENT_SET_COMPLETED,
		ERROR,
		FIELD_COMPLETED,
		FINISHED,
		NEW_ELEMENT,
		PAGE_LOADED,
		PARAMETER_BANNED_WORD_ADDED,
		PARAMETER_CONSTANT_ADDED,
		STARTED,
		SYSTEM_CONTENT_TYPE_ROOT_LOADED
	}
	@XmlEnum
	public enum ParameterType
	{
		@XmlEnumValue(value = "href-banned")
		BANNED_WORD,
		@XmlEnumValue(value = "href-constant")
		CONSTANT
	}
	@XmlType(name = "UnitBrowserVersion")
	@XmlEnum
	public enum UnitBrowserVersion
	{
		CHROME,
		EDGE,
		FIREFOX,
		IE
	}
	public enum WebServiceEventType {
		CONFIGURATION
	}
	public enum XmlEventType {
		MESSAGE_MARSHALLED,
		MESSAGE_UNMARSHALLED,
		SET_UUID
	}
}
