package org.httprobot;

public enum EventType {
	CONTROL_INITIALIZED,
	CONTROL_LOADED,
	PARENT_STARTED,
	PARENT_FINISHED,
	ACTION_WEB_LOADED,
	ALL_PAGES_LOADED,
	DATA_SOURCE_LIST_LOADED,
	DATA_SOURCE_LOADED,
	DOCUMENT_COMPLETED,
	DOCUMENT_INITIALIZED,
	ELEMENT_SET_COMPLETED,
	ERROR,
	FIELD_COMPLETED,
	NEW_ELEMENT,
	PAGE_LOADED,
	PARAMETER_BANNED_WORD_ADDED,
	PARAMETER_CONSTANT_ADDED,
	SYSTEM_CONTENT_TYPE_ROOT_LOADED
}
