package org.httprobot;

public enum ManagerEventType {
	ACTION_WEB_LOADED,
	ALL_PAGES_LOADED,
	DATA_SOURCE_LIST_LOADED,
	DATA_SOURCE_LOADED,
	DOCUMENT_COMPLETED,
	DOCUMENT_INITIALIZED,
	ELEMENT_SET_COMPLETED,
	ERROR,
	FIELD_COMPLETED,
	FINISHED,
	NEW_ELEMENT,
	PAGE_LOADED,
	PARAMETER_BANNED_WORD_ADDED,
	PARAMETER_CONSTANT_ADDED,
	STARTED,
	SYSTEM_CONTENT_TYPE_ROOT_LOADED
}
